#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          disk_prep 
# Required-Start:    $remote_fs $syslog $mysql
# Required-Stop:     $remote_fs $syslog $mysql
# Should-Start:      $network $named $time $mysql
# Should-Stop:       $network $named $time $mysql
# Default-Start:     3
# Default-Stop:      
# Short-Description: Prepare the disk - lvm, xfs, and copy mysql datadir 
# Description:       Prepare the disk - lvm, xfs, and copy mysql datadir 
#                   
### END INIT INFO
#

. /lib/lsb/init-functions

SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)


case "$1" in
  start)
    service mysql stop
    lv_exists=`lvs 2>/dev/null|grep mysql-data`

    if [ -z "${lv_exists}"  ]; then

        # /dev/vdb is mounted ext3, we don't want this
        umount /mnt

        # delete the existing partition, create a new one, tag as LVM
        fdisk /dev/vdb <<EOF
d
n
p
1


t
8e
w
EOF

        # set up of LVM
        pvcreate /dev/vdb1
        vgcreate data /dev/vdb1
        lvcreate --size 20G --name mysql-data data

        # format XFS
        mkfs.xfs /dev/data/mysql-data

        # backup mysql datadir
        mv /var/lib/mysql /var/lib/mysql.bak

        # new mount point
        mkdir /var/lib/mysql

        # set perms
        chown mysql:mysql /var/lib/mysql

        # remove entry for /dev/vdb to mount to /mnt ext3
        sed -i '$d' /etc/fstab

        # add the entry to the fstab for the data directory
        echo -e "\n/dev/data/mysql-data\t/var/lib/mysql\txfs\tdefaults\t0\t0\n" >> /etc/fstab

        # mount
        mount -a

        # copy all the backed up data to the new datadir
        cp -a /var/lib/mysql.bak/* /var/lib/mysql/

        # ensure permissions good
        chown -R mysql:mysql /var/lib/mysql

        # start
        service mysql start

        echo "#!/bin/bash" > /etc/init.d/disk_prep
        echo "exit 0" >> /etc/init.d/disk_prep
    fi     
    ;;
  *)
	echo "Usage: $SELF start"
	exit 1
	;;
esac
