#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          smartagent 
# Required-Start:    $remote_fs $syslog $mysql 
# Required-Stop:     $remote_fs $syslog $mysql
# Should-Start:      $network $mysql
# Should-Stop:       $network $mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the Smart agent 
# Description: 	     Start and stop the Smart agent 
#
### END INIT INFO
#

export PYTHONPATH=/home/nova/reddwarf/swiftapi
SMARTAGENT=/home/nova/reddwarf/smartagent/smartagent_launcher.py

test -x $SMARTAGENT || exit 0

. /lib/lsb/init-functions

SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)

do_start () {
    log_daemon_msg "Starting the smart agent..."
	sudo -u nova $SMARTAGENT start > /dev/null 2>&1 &
    log_daemon_msg "done."

}

do_stop () {
    log_daemon_msg "Stopping the smart agent"
    sudo -u nova $SMARTAGENT stop
}
do_restart() {
    sudo -u nova $SMARTAGENT restart 
}

do_status () {
	smart_agent_pid=`cat /home/nova/lock/smartagent.pid`
	if [ -z $smart_agent_pid ]; then 
        log_failure_msg "The smart agent is not running"
    else 
        log_daemon_msg "The smart agent is running with the PID ${smart_agent_pid}"
    fi
}

#
# main()
#

case "$1" in
  start)
	# Start daemon
    do_start
	;;
  stop)
    do_stop
	;;
  restart)
    do_restart
	;;
  status)
    do_status
	;;
  *)
	echo "Usage: $SELF start|stop|restart|status"
	exit 1
	;;
esac
